# Generated by Django 2.2.7 on 2019-12-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
