# Generated by Django 2.2.7 on 2020-02-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-order']},
        ),
    ]
