# Generated by Django 3.0 on 2020-02-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200207_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAbout',
            new_name='AboutMe',
        ),
    ]
