# Generated by Django 2.2.7 on 2020-07-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200207_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
