# Generated by Django 2.2.7 on 2020-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_color',
            field=models.CharField(default='', max_length=255),
        ),
    ]
