# Generated by Django 2.2.7 on 2020-07-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_skill_skill_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
