# Generated by Django 2.2.7 on 2020-07-14 19:10

from django.db import migrations, models
import django_resized.forms
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200713_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('github', models.URLField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[696, 500], upload_to=main.utils.get_propic_name),
        ),
    ]
