# Generated by Django 2.2.7 on 2020-07-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200714_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.AddField(
            model_name='location',
            name='house_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
