# Generated by Django 2.2.7 on 2020-12-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200714_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-order']},
        ),
    ]
